#!/bin/bash

OK=0
WARN=1
CRIT=2

check() {
  cat /proc/mdstat

  for dev in $(ls /dev/md*); do
    local detail="$(mdadm --detail ${dev})"

    local degraded=$(echo "${detail}" | grep 'State : ' | grep degraded | wc -l)
    local failed=$(echo "${detail}" | grep 'State : ' | grep FAILED | wc -l)

    local failed_dev=$(echo "${detail}" | grep 'Failed Devices : ' | awk '{print $4}')

    if [ $failed -gt 0 -o $degraded -gt 0 ]; then
      exit $CRIT
    elif [ $failed_dev -gt 0 ]; then
      exit $WARN
    fi
  done

  exit $OK
}

check

